log:
  disable_sentry: true
  level: info

listener:
  addr: :8005

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: price-svc
  service_port: 80

connector:
  url: http://localhost:81/integrations
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiMHg0MDk3NDhkZmIzMWNhMTQyNGQxMzE2NjM5MThjN2E0NWYyZWE2NTA3IiwicHVycG9zZSI6InNlc3Npb24iLCJleHAiOjMyODY4MDU0NzR9.5Z7FBn4UrgjaNNOGSy0j98cb3M9san4A8kvGzq98Fsg

coingecko:
  expiration: 10m
  url: https://api.coingecko.com/api/v3 # https://pro-api.coingecko.com/api/v3 for paid plan
  api_key: # for paid plan

mocked:
  tokens:
    - actual_address: 0xEe84b9D1F5320bC498d39C38Dd90242CE9E8fa34
      coingecko_address: 0xdac17f958d2ee523a2206206994597c13d831ec7
    - actual_address: 0xE7443eBe40ca97be34C1a40abB54B1Bd432B6C82
      coingecko_address: 0x0d8775f648430679a709e98d2b0cb6250d2887ef
    - actual_address: 0x3f2c8CC564A37e4be666Bb6dDCfC568Eb7DB4019
      coingecko_address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
  nfts:
    - actual_address: 0xEe84b9D1F5320bC498d39C38Dd90242CE9E8fa34
      coingecko_address: 0x6609e542e0626bc3fc2110f0ead172030fbe97ab # ethereum platform
  platforms:
    - id: "q"
      chain_id: 35441
      name: "Q"
      short_name: "Q"
      price_per_one_token: "1.0" # string in USD
      price_per_one_nft: "1.0" # string in USD
    - id: "polygon-pos"
      chain_id: 137
      name: "Polygon POS"
      short_name: "MATIC"
    - id: "ethereum"
      chain_id: 1
      name: "Ethereum"
      short_name: ""